-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Database.Object.Lehrplan_intern exposing (..)

import Database.InputObject
import Database.Interface
import Database.Object
import Database.Scalar
import Database.ScalarCodecs
import Database.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


bundesland : SelectionSet Database.ScalarCodecs.Bundesland Database.Object.Lehrplan_intern
bundesland =
    Object.selectionForField "ScalarCodecs.Bundesland" "bundesland" [] (Database.ScalarCodecs.codecs |> Database.Scalar.unwrapCodecs |> .codecBundesland |> .decoder)


fach : SelectionSet String Database.Object.Lehrplan_intern
fach =
    Object.selectionForField "String" "fach" [] Decode.string


klassenstufe : SelectionSet Int Database.Object.Lehrplan_intern
klassenstufe =
    Object.selectionForField "Int" "klassenstufe" [] Decode.int


{-| An object relationship
-}
lehrplandetail :
    SelectionSet decodesTo Database.Object.Lehrplandetails
    -> SelectionSet decodesTo Database.Object.Lehrplan_intern
lehrplandetail object_ =
    Object.selectionForCompositeField "lehrplandetail" [] object_ identity


lehrplanid : SelectionSet Int Database.Object.Lehrplan_intern
lehrplanid =
    Object.selectionForField "Int" "lehrplanid" [] Decode.int


schulart_intern : SelectionSet String Database.Object.Lehrplan_intern
schulart_intern =
    Object.selectionForField "String" "schulart_intern" [] Decode.string
