-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Database.Object.Lernplattform exposing (..)

import Database.InputObject
import Database.Interface
import Database.Object
import Database.Scalar
import Database.ScalarCodecs
import Database.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


bundesland : SelectionSet (Maybe Database.ScalarCodecs.Bundesland) Database.Object.Lernplattform
bundesland =
    Object.selectionForField "(Maybe ScalarCodecs.Bundesland)" "bundesland" [] (Database.ScalarCodecs.codecs |> Database.Scalar.unwrapCodecs |> .codecBundesland |> .decoder |> Decode.nullable)


downvotes : SelectionSet (Maybe Int) Database.Object.Lernplattform
downvotes =
    Object.selectionForField "(Maybe Int)" "downvotes" [] (Decode.int |> Decode.nullable)


fach : SelectionSet (Maybe String) Database.Object.Lernplattform
fach =
    Object.selectionForField "(Maybe String)" "fach" [] (Decode.string |> Decode.nullable)


klassenstufe : SelectionSet (Maybe Int) Database.Object.Lernplattform
klassenstufe =
    Object.selectionForField "(Maybe Int)" "klassenstufe" [] (Decode.int |> Decode.nullable)


lehrplanbeschreibung : SelectionSet (Maybe String) Database.Object.Lernplattform
lehrplanbeschreibung =
    Object.selectionForField "(Maybe String)" "lehrplanbeschreibung" [] (Decode.string |> Decode.nullable)


lehrplaneintragsdatum : SelectionSet (Maybe Database.ScalarCodecs.Date) Database.Object.Lernplattform
lehrplaneintragsdatum =
    Object.selectionForField "(Maybe ScalarCodecs.Date)" "lehrplaneintragsdatum" [] (Database.ScalarCodecs.codecs |> Database.Scalar.unwrapCodecs |> .codecDate |> .decoder |> Decode.nullable)


lehrplanelternid : SelectionSet (Maybe Int) Database.Object.Lernplattform
lehrplanelternid =
    Object.selectionForField "(Maybe Int)" "lehrplanelternid" [] (Decode.int |> Decode.nullable)


lehrplanhierarchie : SelectionSet (Maybe String) Database.Object.Lernplattform
lehrplanhierarchie =
    Object.selectionForField "(Maybe String)" "lehrplanhierarchie" [] (Decode.string |> Decode.nullable)


lehrplanquelle : SelectionSet (Maybe String) Database.Object.Lernplattform
lehrplanquelle =
    Object.selectionForField "(Maybe String)" "lehrplanquelle" [] (Decode.string |> Decode.nullable)


lehrplantitel : SelectionSet (Maybe String) Database.Object.Lernplattform
lehrplantitel =
    Object.selectionForField "(Maybe String)" "lehrplantitel" [] (Decode.string |> Decode.nullable)


link : SelectionSet (Maybe String) Database.Object.Lernplattform
link =
    Object.selectionForField "(Maybe String)" "link" [] (Decode.string |> Decode.nullable)


materialart : SelectionSet (Maybe Database.ScalarCodecs.Ressourcenart) Database.Object.Lernplattform
materialart =
    Object.selectionForField "(Maybe ScalarCodecs.Ressourcenart)" "materialart" [] (Database.ScalarCodecs.codecs |> Database.Scalar.unwrapCodecs |> .codecRessourcenart |> .decoder |> Decode.nullable)


materialbeschreibung : SelectionSet (Maybe String) Database.Object.Lernplattform
materialbeschreibung =
    Object.selectionForField "(Maybe String)" "materialbeschreibung" [] (Decode.string |> Decode.nullable)


materialeintragsdatum : SelectionSet (Maybe Database.ScalarCodecs.Date) Database.Object.Lernplattform
materialeintragsdatum =
    Object.selectionForField "(Maybe ScalarCodecs.Date)" "materialeintragsdatum" [] (Database.ScalarCodecs.codecs |> Database.Scalar.unwrapCodecs |> .codecDate |> .decoder |> Decode.nullable)


materialtestdatum : SelectionSet (Maybe Database.ScalarCodecs.Date) Database.Object.Lernplattform
materialtestdatum =
    Object.selectionForField "(Maybe ScalarCodecs.Date)" "materialtestdatum" [] (Database.ScalarCodecs.codecs |> Database.Scalar.unwrapCodecs |> .codecDate |> .decoder |> Decode.nullable)


materialtitel : SelectionSet (Maybe String) Database.Object.Lernplattform
materialtitel =
    Object.selectionForField "(Maybe String)" "materialtitel" [] (Decode.string |> Decode.nullable)


modul : SelectionSet (Maybe String) Database.Object.Lernplattform
modul =
    Object.selectionForField "(Maybe String)" "modul" [] (Decode.string |> Decode.nullable)


schulart : SelectionSet (Maybe String) Database.Object.Lernplattform
schulart =
    Object.selectionForField "(Maybe String)" "schulart" [] (Decode.string |> Decode.nullable)


upvotes : SelectionSet (Maybe Int) Database.Object.Lernplattform
upvotes =
    Object.selectionForField "(Maybe Int)" "upvotes" [] (Decode.int |> Decode.nullable)
