-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Database.Object.Materialzuordnung exposing (..)

import Database.InputObject
import Database.Interface
import Database.Object
import Database.Scalar
import Database.ScalarCodecs
import Database.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


link : SelectionSet String Database.Object.Materialzuordnung
link =
    Object.selectionForField "String" "link" [] Decode.string


{-| An object relationship
-}
material :
    SelectionSet decodesTo Database.Object.Material
    -> SelectionSet decodesTo Database.Object.Materialzuordnung
material object_ =
    Object.selectionForCompositeField "material" [] object_ identity


modul : SelectionSet String Database.Object.Materialzuordnung
modul =
    Object.selectionForField "String" "modul" [] Decode.string


{-| An object relationship
-}
module_ :
    SelectionSet decodesTo Database.Object.Module
    -> SelectionSet decodesTo Database.Object.Materialzuordnung
module_ object_ =
    Object.selectionForCompositeField "module" [] object_ identity
