-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Database.Enum.Lernplattform_select_column exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| select columns of table "lernplattform"

  - Bundesland - column name
  - Downvotes - column name
  - Fach - column name
  - Klassenstufe - column name
  - Lehrplanbeschreibung - column name
  - Lehrplaneintragsdatum - column name
  - Lehrplanelternid - column name
  - Lehrplanhierarchie - column name
  - Lehrplanquelle - column name
  - Lehrplantitel - column name
  - Link - column name
  - Materialart - column name
  - Materialbeschreibung - column name
  - Materialeintragsdatum - column name
  - Materialtestdatum - column name
  - Materialtitel - column name
  - Modul - column name
  - Schulart - column name
  - Upvotes - column name

-}
type Lernplattform_select_column
    = Bundesland
    | Downvotes
    | Fach
    | Klassenstufe
    | Lehrplanbeschreibung
    | Lehrplaneintragsdatum
    | Lehrplanelternid
    | Lehrplanhierarchie
    | Lehrplanquelle
    | Lehrplantitel
    | Link
    | Materialart
    | Materialbeschreibung
    | Materialeintragsdatum
    | Materialtestdatum
    | Materialtitel
    | Modul
    | Schulart
    | Upvotes


list : List Lernplattform_select_column
list =
    [ Bundesland, Downvotes, Fach, Klassenstufe, Lehrplanbeschreibung, Lehrplaneintragsdatum, Lehrplanelternid, Lehrplanhierarchie, Lehrplanquelle, Lehrplantitel, Link, Materialart, Materialbeschreibung, Materialeintragsdatum, Materialtestdatum, Materialtitel, Modul, Schulart, Upvotes ]


decoder : Decoder Lernplattform_select_column
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "bundesland" ->
                        Decode.succeed Bundesland

                    "downvotes" ->
                        Decode.succeed Downvotes

                    "fach" ->
                        Decode.succeed Fach

                    "klassenstufe" ->
                        Decode.succeed Klassenstufe

                    "lehrplanbeschreibung" ->
                        Decode.succeed Lehrplanbeschreibung

                    "lehrplaneintragsdatum" ->
                        Decode.succeed Lehrplaneintragsdatum

                    "lehrplanelternid" ->
                        Decode.succeed Lehrplanelternid

                    "lehrplanhierarchie" ->
                        Decode.succeed Lehrplanhierarchie

                    "lehrplanquelle" ->
                        Decode.succeed Lehrplanquelle

                    "lehrplantitel" ->
                        Decode.succeed Lehrplantitel

                    "link" ->
                        Decode.succeed Link

                    "materialart" ->
                        Decode.succeed Materialart

                    "materialbeschreibung" ->
                        Decode.succeed Materialbeschreibung

                    "materialeintragsdatum" ->
                        Decode.succeed Materialeintragsdatum

                    "materialtestdatum" ->
                        Decode.succeed Materialtestdatum

                    "materialtitel" ->
                        Decode.succeed Materialtitel

                    "modul" ->
                        Decode.succeed Modul

                    "schulart" ->
                        Decode.succeed Schulart

                    "upvotes" ->
                        Decode.succeed Upvotes

                    _ ->
                        Decode.fail ("Invalid Lernplattform_select_column type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Lernplattform_select_column -> String
toString enum =
    case enum of
        Bundesland ->
            "bundesland"

        Downvotes ->
            "downvotes"

        Fach ->
            "fach"

        Klassenstufe ->
            "klassenstufe"

        Lehrplanbeschreibung ->
            "lehrplanbeschreibung"

        Lehrplaneintragsdatum ->
            "lehrplaneintragsdatum"

        Lehrplanelternid ->
            "lehrplanelternid"

        Lehrplanhierarchie ->
            "lehrplanhierarchie"

        Lehrplanquelle ->
            "lehrplanquelle"

        Lehrplantitel ->
            "lehrplantitel"

        Link ->
            "link"

        Materialart ->
            "materialart"

        Materialbeschreibung ->
            "materialbeschreibung"

        Materialeintragsdatum ->
            "materialeintragsdatum"

        Materialtestdatum ->
            "materialtestdatum"

        Materialtitel ->
            "materialtitel"

        Modul ->
            "modul"

        Schulart ->
            "schulart"

        Upvotes ->
            "upvotes"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Lernplattform_select_column
fromString enumString =
    case enumString of
        "bundesland" ->
            Just Bundesland

        "downvotes" ->
            Just Downvotes

        "fach" ->
            Just Fach

        "klassenstufe" ->
            Just Klassenstufe

        "lehrplanbeschreibung" ->
            Just Lehrplanbeschreibung

        "lehrplaneintragsdatum" ->
            Just Lehrplaneintragsdatum

        "lehrplanelternid" ->
            Just Lehrplanelternid

        "lehrplanhierarchie" ->
            Just Lehrplanhierarchie

        "lehrplanquelle" ->
            Just Lehrplanquelle

        "lehrplantitel" ->
            Just Lehrplantitel

        "link" ->
            Just Link

        "materialart" ->
            Just Materialart

        "materialbeschreibung" ->
            Just Materialbeschreibung

        "materialeintragsdatum" ->
            Just Materialeintragsdatum

        "materialtestdatum" ->
            Just Materialtestdatum

        "materialtitel" ->
            Just Materialtitel

        "modul" ->
            Just Modul

        "schulart" ->
            Just Schulart

        "upvotes" ->
            Just Upvotes

        _ ->
            Nothing
