/* {
  "Physik": {
    "Baden-Württemberg": {
      "11": "#11-12",
      "11-12": {
        "Basisfach mit Schwerpunkt Quantenphysik": [
          "Empirismus",
          "Modelle in der Physik",
          "Modellvorstellung von Licht",
          "Modellvorstellung von Materie",
          "Naturkonstanten",
          "Planck'sche Konstante",
          "elektrische Feldlinien",
          "magnetische Feldlinien",
          "homogene und nichthomogene Felder",
          "Zusammenhang zwischen der Kraftwirkung auf eine Probeladung und der elektrischen Feldstärke",
          "Zusammenhang zwischen der Kraftwirkung auf einen stromdurchflossenen Leiter und der magnetischen Flussdichte",
          "Plattenkondensator",
          "schlanke Spule",
          "magnetische vs. elektrische Felder",
          "elektrische vs. Gravitationsfelder",
          "Gravitations- vs. magnetische Felder",
          "Lorentzkraft",
          "Faraday'sches Induktionsgesetz",
          "magnetischer Fluss",
          "Lenz'sche Regel",
          "Selbstinduktionseffekte",
          "Induktivität",
          "Generator",
          "Transformator",
          "Induktionsladegerät",
          "Induktionskochplatte",
          "Maxwell-Gleichungen",
          "Schwingungs-Experimente",
          "Schwingungen als zeitlich periodische Bewegungen um eine Gleichgewichtslage",
          "ungedämpfte harmonische Schwingungen",
          "Zusammenhang zwischen harmonischen mechanischen Schwingungen und linearer Rückstellkraft",
          "Federpendel",
          "elektromagnetischer Schwingkreis",
          "mechanische vs. elektromagnetische Schwingungen",
          "Wellenlänge",
          "Ausbreitungsgeschwindigkeit",
          "Wellenfront",
          "Transversalwelle",
          "Beugung",
          "Reflexion",
          "Brechung",
          "Interferenz",
          "Energietransport",
          "Meereswellen",
          "Gegenschall",
          "eindimensionale stehende Welle",
          "Wellenbäuche",
          "Wellenknoten",
          "konstruktive und destruktive Interferenz",
          "Gangunterschied",
          "Huygens'sches Prinzip",
          "Doppler-Effekt",
          "Rot- und Blauverschiebung",
          "elektromagnetisches Spektrum",
          "kohärentes Licht als elektromagnetische Welle",
          "Lichtgeschwindigkeit",
          "Strahlenmodell vs. Wellenmodell des Lichts",
          "Lichtbeugung an einer Blende",
          "Dispersion",
          "Interferenzmuster bei Lichtbeugung an Doppelspalt und Gitter",
          "Intensitätsverteilung  bei Lichtbeugung an Doppelspalt und Gitter",
          "Interferenz-Minima und -Maxima bei Lichtbeugung an Doppelspalt und Gitter",
          "Experiment: Interferenzphänomene an Doppelspalt und Gitter",
          "Interferenz an dünnen Schichten",
          "Interferenz an Gitterstrukturen",
          "Laser-Speckle",
          "klassische Wellen, klassische Teilchen, und Quantenobjekte am Doppelspalt",
          "Ersetzung des Determinismus durch Wahrscheinlichkeitsaussagen für Quantenobjekte",
          "Experimente zur Interferenz einzelner Quantenobjekte",
          "Unmöglichkeit der unabhängigen Beobachtung von Wellen- und Teilcheneigenschaften",
          "Interferenzfähigkeit von Quantenobjekten",
          "Interferenzfähigkeit am Doppelspalt",
          "Interferenzfähigkeit am Mach-Zehnder-Interferometer",
          "lichtelektrischer Effekt",
          "Einstein'sche Lichtquantenhypothese",
          "Hallwachs-Effekt",
          "Einstein'sche Gleichung",
          "Planck'sche Konstante",
          "Energie und Impuls von Quantenobjekten",
          "de Broglie-Wellenlänge von Materiewellen"
        ],
        "Basisfach mit Schwerpunkt Astrophysik": [
          "Empirismus",
          "Modelle in der Physik",
          "Astronomie als Anwendungswissenschaft von Physik und Chemie",
          "Bildgebung",
          "Spektroskopie",
          "Teleskope",
          "Detektoren",
          "Modellvorstellung von Licht",
          "Modellvorstellung von Materie",
          "zeitliche Entwicklung des Kosmos",
          "Urknall",
          "Naturkonstanten",
          "Planck'sche Konstante",
          "Astronomische Einheit",
          "Lichtjahr",
          "Parsec",
          "Sonnenmasse",
          "Sonnenleuchtkraft",
          "elektrische Feldlinien",
          "magnetische Feldlinien",
          "homogene und nichthomogene Felder",
          "Zusammenhang zwischen der Kraftwirkung auf eine Probeladung und der elektrischen Feldstärke",
          "Zusammenhang zwischen der Kraftwirkung auf einen stromdurchflossenen Leiter und der magnetischen Flussdichte",
          "magnetische vs. elektrische Felder",
          "elektrische vs. Gravitationsfelder",
          "Gravitations- vs. magnetische Felder",
          "Lorentzkraft",
          "Faraday'sches Induktionsgesetz",
          "magnetischer Fluss",
          "Lenz'sche Regel",
          "Generator",
          "Transformator",
          "Induktionsladegerät",
          "Induktionskochplatte",
          "Maxwell-Gleichungen",
          "Schwingungs-Experimente",
          "Schwingungen als zeitlich periodische Bewegungen um eine Gleichgewichtslage",
          "ungedämpfte harmonische Schwingungen",
          "Zusammenhang zwischen harmonischen mechanischen Schwingungen und linearer Rückstellkraft",
          "Federpendel",
          "Wellenlänge",
          "Ausbreitungsgeschwindigkeit",
          "Wellenfront",
          "Transversalwelle",
          "Beugung",
          "Reflexion",
          "Brechung",
          "Interferenz",
          "Energietransport",
          "Gangunterschied",
          "Huygens'sches Prinzip",
          "Doppler-Effekt",
          "Rot- und Blauverschiebung",
          "elektromagnetisches Spektrum",
          "elektromagnetische vs. Gravitationswellen",
          "Ausbreitung im Vakuum",
          "kohärentes Licht als elektromagnetische Welle",
          "Lichtgeschwindigkeit",
          "Strahlenmodell vs. Wellenmodell des Lichts",
          "Lichtbeugung an einer Blende",
          "Dispersion",
          "Interferenzmuster bei Lichtbeugung an Doppelspalt und Gitter",
          "Intensitätsverteilung  bei Lichtbeugung an Doppelspalt und Gitter",
          "Interferenz-Minima und -Maxima bei Lichtbeugung an Doppelspalt und Gitter",
          "Experiment: Interferenzphänomene an Doppelspalt und Gitter",
          "Experiment: Spektren verschiedener Lichtquellen",
          "Atomaufbau",
          "lichtelektrischer Effekt",
          "einstein'sche Lichtquantenhypothese",
          "Hallwachs-Effekt",
          "Einstein'sche Gleichung",
          "Planck'sche Konstante",
          "Energie und Impuls von Quantenobjekten",
          "de-Broglie Wellenlänge von Materiewellen",
          "kontinuierliche Spektren",
          "Linienspektren",
          "Emissionsspektren",
          "Absorptionsspektren",
          "Bohr'sche Frequenzbedingung",
          "Atmosphären von Sternen und Planeten",
          "interstellares Gas",
          "Molekülwolken",
          "Kernfusion",
          "Bindungsenergie",
          "pp-Kette",
          "Urknall",
          "kosmische Expansion",
          "Alter des Universums",
          "Hintergrundstrahlung",
          "Entstehung der Atome",
          "Entstehung von Galaxien",
          "Galaxien als zusammengesetzte Systeme",
          "dunkle Materie",
          "Rotverschiebung",
          "Hubble-Relation",
          "kosmischer Skalenfaktor",
          "Abhängigkeit der Stabilität von kosmischen Objekten von der Gravitation entgegenwirkendem Druck",
          "Vor-Hauptreihenentwicklung",
          "Gravitation und innerer Gasdruck von Molekülwolken",
          "Bedingungen für den Kollaps von Molekülwolken",
          "Energieabstrahlung beim Kollaps von Molekülwolken",
          "Protostern",
          "Einsetzen von Fusionsprozessen",
          "Hauptreihenstadium",
          "Gravitation und innerer Gasdruck",
          "Kernfusion",
          "Energietransport zur Oberfläche",
          "temperaturabhängige Abstrahlung",
          "Sonne als Stern",
          "Nach-Hauptreihenentwicklung",
          "Schalenbrennen",
          "Roter Riese",
          "Zukunft der Sonne",
          "Kriterien für die Stabilität der Endstadien",
          "Weißer Zwerg",
          "Neutronenstern",
          "Schwarzes Loch",
          "Schwarzschildradius",
          "Nachweismethoden für extrasolare Planeten",
          "Transitmethode",
          "Radialgeschwindigkeitsmethode",
          "astrometrische Methode",
          "Mikrogravitationslinsenmethode",
          "direkte Abbildung",
          "Spektralanalyse von Plantenatmosphären"
        ],
        "Leistungsfach": [
          "Empirismus",
          "Modelle in der Physik",
          "Modellvorstellung von Licht",
          "Modellvorstellung von Materie",
          "Naturkonstanten",
          "Planck'sche Konstante",
          "Kraftwirkung zwischen elektrisch geladenen Körpern",
          "elektrische Feldlinien",
          "homogene und nichthomogene Felder",
          "Feld einer Punktladung",
          "Feld eines Dipols",
          "Quelle und Senke",
          "Zusammenhang zwischen der Kraftwirkung auf eine Probeladung und der elektrischen Feldstärke",
          "elektrische Feldstärke",
          "Plattenkondensator",
          "Kapazität",
          "Kondensator",
          "zeitabhängiger Auf- und Entladevorgang eines Kondensators",
          "Spannung",
          "Potential",
          "Äquipotentiallinien von homogenen und Dipol-Feldern",
          "elektrische vs. Gravitationsfelder",
          "Bewegung geladener Teilchen am homogenen Feld",
          "magnetisches Feld um einen geraden Leiter",
          "Handregel",
          "magnetischer Fluss",
          "magnetische FLussdichte",
          "Lorentzkraft",
          "Drei-Finger-Regel",
          "Faraday'sches Induktionsgesetz",
          "magnetischer Fluss",
          "Lenz'sche Regel",
          "Selbstinduktionseffekte",
          "Induktivität",
          "Generator",
          "Transformator",
          "Induktionsladegerät",
          "Induktionskochplatte",
          "Maxwell-Gleichungen",
          "Schwingungs-Experimente",
          "Schwingungen als zeitlich periodische Bewegungen um eine Gleichgewichtslage",
          "ungedämpfte harmonische Schwingungen",
          "Zusammenhang zwischen harmonischen mechanischen Schwingungen und linearer Rückstellkraft",
          "Federpendel",
          "elektromagnetischer Schwingkreis",
          "mechanische vs. elektromagnetische Schwingungen",
          "Wellenlänge",
          "Ausbreitungsgeschwindigkeit",
          "Wellenfront",
          "Transversalwelle",
          "Beugung",
          "Reflexion",
          "Brechung",
          "Interferenz",
          "Energietransport",
          "Meereswellen",
          "Gegenschall",
          "eindimensionale stehende Welle",
          "Wellenbäuche",
          "Wellenknoten",
          "konstruktive und destruktive Interferenz",
          "Gangunterschied",
          "Huygens'sches Prinzip",
          "Doppler-Effekt",
          "Rot- und Blauverschiebung",
          "elektromagnetisches Spektrum",
          "kohärentes Licht als elektromagnetische Welle",
          "Lichtgeschwindigkeit",
          "Strahlenmodell vs. Wellenmodell des Lichts",
          "Lichtbeugung an einer Blende",
          "Dispersion",
          "Interferenzmuster bei Lichtbeugung an Doppelspalt und Gitter",
          "Intensitätsverteilung  bei Lichtbeugung an Doppelspalt und Gitter",
          "Interferenz-Minima und -Maxima bei Lichtbeugung an Doppelspalt und Gitter",
          "Experiment: Interferenzphänomene an Doppelspalt und Gitter",
          "Interferenz an dünnen Schichten",
          "Interferenz an Gitterstrukturen",
          "Laser-Speckle",
          "klassische Wellen, klassische Teilchen, und Quantenobjekte am Doppelspalt",
          "Ersetzung des Determinismus durch Wahrscheinlichkeitsaussagen für Quantenobjekte",
          "Experimente zur Interferenz einzelner Quantenobjekte",
          "Unmöglichkeit der unabhängigen Beobachtung von Wellen- und Teilcheneigenschaften",
          "Interferenzfähigkeit von Quantenobjekten",
          "Interferenzfähigkeit am Doppelspalt",
          "Interferenzfähigkeit am Mach-Zehnder-Interferometer",
          "lichtelektrischer Effekt",
          "Einstein'sche Lichtquantenhypothese",
          "Hallwachs-Effekt",
          "Einstein'sche Gleichung",
          "Planck'sche Konstante",
          "Energie und Impuls von Quantenobjekten",
          "de Broglie-Wellenlänge von Materiewellen"
        ]
      }
    }
  }
} */