-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Database.Object exposing (..)


type Lehrplan
    = Lehrplan


type Lehrplan_intern
    = Lehrplan_intern


type Lehrplandetails
    = Lehrplandetails


type Lehrplanzuordnung
    = Lehrplanzuordnung


type Lernplattform
    = Lernplattform


type Material
    = Material


type Materialzuordnung
    = Materialzuordnung


type Module
    = Module


type Modulhierarchie
    = Modulhierarchie


type Schulart
    = Schulart


type Schulartenbedeutung
    = Schulartenbedeutung
